import { useState, useRef, useEffect } from 'react';
import axios from 'axios';
import { Send, Map, Sun, Utensils, Info } from 'lucide-react';
import './index.css';

function App() {
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId] = useState(() => Math.random().toString(36).substring(7));
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async (e, customText = null) => {
    e?.preventDefault();
    const textToSend = customText || input;
    
    if (!textToSend.trim()) return;

    // Add user message immediately
    const userMsg = { id: Date.now(), text: textToSend, sender: 'user' };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    try {
      const response = await axios.post('http://localhost:8000/api/v1/chat', {
        session_id: sessionId,
        message: textToSend
      });

      const botMsg = { id: Date.now() + 1, text: response.data.response, sender: 'bot' };
      setMessages(prev => [...prev, botMsg]);
    } catch (error) {
      console.error("Chat Error:", error);
      const errorMsg = { 
        id: Date.now() + 1, 
        text: "Sorry, I'm having trouble connecting right now. Please try again later.", 
        sender: 'bot' 
      };
      setMessages(prev => [...prev, errorMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="app-container">
      <header className="header">
        <div className="header-title">
          <Map color="#ff9966" size={28} />
          <div>
            <h1>Odisha Explorer</h1>
            <p className="header-subtitle">Your intelligent travel companion</p>
          </div>
        </div>
      </header>

      <div className="chat-area">
        {messages.length === 0 ? (
          <div className="welcome-screen">
            <h2>Discover India's Best Kept Secret</h2>
            <p>Ask me anything about Odisha's heritage, food, weather, or let me plan a complete trip for you.</p>
            
            <div className="features-grid">
              <div className="feature-card" onClick={() => handleSend(null, "I would like to plan a trip to Odisha.")}>
                <Map className="feature-icon" size={24} />
                <span>Trip Planning</span>
              </div>
              <div className="feature-card" onClick={() => handleSend(null, "I want to check the live weather for a location.")}>
                <Sun className="feature-icon" size={24} />
                <span>Live Weather</span>
              </div>
              <div className="feature-card" onClick={() => handleSend(null, "I want to know about the local cuisine in Odisha.")}>
                <Utensils className="feature-icon" size={24} />
                <span>Local Cuisine</span>
              </div>
              <div className="feature-card" onClick={() => handleSend(null, "Tell me about heritage sites and their guidelines.")}>
                <Info className="feature-icon" size={24} />
                <span>Heritage Info</span>
              </div>
            </div>
          </div>
        ) : (
          <>
            {messages.map((msg) => (
              <div key={msg.id} className={`message-wrapper ${msg.sender}`}>
                <div className="message">
                  {/* Basic markdown parsing for bold text generated by LLM */}
                  {msg.text.split('\n').map((line, i) => (
                    <p key={i} dangerouslySetInnerHTML={{__html: line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}} />
                  ))}
                </div>
                <span className="message-time">
                  {new Date(msg.id).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
            ))}
            
            {isLoading && (
              <div className="typing-indicator">
                <div className="dot"></div>
                <div className="dot"></div>
                <div className="dot"></div>
              </div>
            )}
            <div ref={messagesEndRef} />
          </>
        )}
      </div>

      <form className="input-area" onSubmit={handleSend}>
        <div className="input-wrapper">
          <input
            type="text"
            className="chat-input"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Type your message..."
            disabled={isLoading}
          />
        </div>
        <button type="submit" className="send-button" disabled={!input.trim() || isLoading}>
          <Send size={20} />
        </button>
      </form>
    </div>
  );
}

export default App;
